language: node_js
dist: xenial
cache: yarn
env:
  global:
    - CXX=g++-4.8
    - YARN_VERSION=1.16.0

jobs:
  include:
    - name: Node.js 8
      node_js:
        - 8
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
      script:
        - yarn run mocha-suite
    - name: Node.js 10
      node_js:
        - 10
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
      script:
        - yarn run mocha-suite
    - name: Node.js 12
      node_js:
        - 12
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$YARN_VERSION"
        - export PATH="$HOME/.yarn/bin:$PATH"
      script:
        - yarn run mocha-suite
    - name: eslint
      script:
        - yarn run eslint
      language: generic
    - name: ShellCheck
      script:
        - shellcheck bin/heroku bin/setup
      language: generic
    - name: json-lint
      addons:
        apt:
          packages:
          - jq
      script:
        - yarn run jsonlint
      language: generic
